version: '3'

services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    image: supelec
    container_name: jupyter
    restart: unless-stopped
    entrypoint: "start.sh jupyter notebook --NotebookApp.token=''"
    ports:
      - "8888:8888"
    volumes:
      - $PWD/work:/home/jovyan/work